#!/bin/bash
export TMPDIR=/home/skylinehs/apps/shs-attendance/tmp
export LD_LIBRARY_PATH=/usr/sqlite330/lib
mkdir -p /home/skylinehs/apps/shs-attendance/tmp
PIDFILE="/home/skylinehs/apps/shs-attendance/tmp/uwsgi.pid"

if [ -e "$PIDFILE" ] && (pgrep -u skylinehs | grep -x -f $PIDFILE &> /dev/null); then
  echo "uWSGI for shs-attendance already running."
  exit 99
fi

/home/skylinehs/apps/shs-attendance/env/bin/uwsgi --ini /home/skylinehs/apps/shs-attendance/uwsgi.ini

echo "Started uWSGI for shs-attendance."
