#!/bin/bash
PIDFILE="/home/skylinehs/apps/shs-attendance/tmp/uwsgi.pid"

if [ ! -e "$PIDFILE" ]; then
    echo "$PIDFILE missing, maybe uWSGI is already stopped?"
    exit 99
fi

PID=$(cat $PIDFILE)

if [ -e "$PIDFILE" ] && (pgrep -u skylinehs | grep -x -f $PIDFILE &> /dev/null); then
  /home/skylinehs/apps/shs-attendance/env/bin/uwsgi --stop $PIDFILE
  sleep 3
fi

if [ -e "$PIDFILE" ] && (pgrep -u skylinehs | grep -x -f $PIDFILE &> /dev/null); then
  echo "uWSGI did not stop, killing it."
  sleep 3
  kill -9 $PID
fi
rm -f $PIDFILE
echo "Stopped."
